
seed: 42
data_dir: data
output_dir: outputs
img_size: 224
batch_size: 32
num_workers: 4
epochs: 20
learning_rate: 0.0003
model: mobilenet_v2   # one of: mobilenet_v2, resnet50, vgg16, baseline_cnn
freeze_backbone: true
unfreeze: false
amp: true
